Cristian
Bedu6/CH1Red pull request #1
Opened 2019-01-18 22:04 UTC by CrisESC93

Saludos, les dejo mi código para su revisión.

Cualquier corrección y/o sugerencia será bienvenida.

¡¡¡Gracias!!!

2019-01-18 22:29 UTC, RodolfoSaldivar requested changes

2019-01-18 22:29 UTC, RodolfoSaldivar commented on css/cristian.css
> +    padding: 0 32px;
Hace que se vean espacios blancos al lado cuando no es móvil, viene desde el sass.

2019-01-18 22:29 UTC, RodolfoSaldivar commented on scss/cristian/_cristianMediaQueries.scss
> +        padding: 0 32px;
Ver el comentario anterior.

2019-01-18 22:35 UTC, CrisESC93 commented on css/cristian.css
> +    padding: 0 32px;
Así es, lo dejé así debido a que el sitio de Ford maneja márgenes laterales aún más grandes en pantallas grandes.
![ford](https://user-images.githubusercontent.com/22949902/51416399-f8f15a80-1b3e-11e9-8053-9c71b2145616.png)

2019-01-18 22:42 UTC, RodolfoSaldivar approved these changes

2019-01-19 02:18 UTC, amilcaralex97 approved these changes

2019-01-19 03:07 UTC, merged